name: Auto Pull Request - test-1 to main

on:
  push:
    branches: [test-1]
  workflow_dispatch:

jobs:
  auto-create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Sync branches
        uses: TreTuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: test-1
          TO_BRANCH: main
          PULL_REQUEST_TITLE: "[Auto Create PR] Merge from test-1 To main"